ANIM_DATA_END_FRAME_COUNT equ 32
ANIM_DATA_END_POINTERS:
/*
	DW ANIM_DATA_END
	DW ANIM_DATA_END.f1
	DW ANIM_DATA_END.f2
	DW ANIM_DATA_END.f3
	DW ANIM_DATA_END.f4
	DW ANIM_DATA_END.f5
	DW ANIM_DATA_END.f6
	DW ANIM_DATA_END.f7
*/
	DW ANIM_DATA_END.f8
	DW ANIM_DATA_END.f9
	DW ANIM_DATA_END.f10
	DW ANIM_DATA_END.f11
	DW ANIM_DATA_END.f12
	DW ANIM_DATA_END.f13
	DW ANIM_DATA_END.f14
	DW ANIM_DATA_END.f15
	DW ANIM_DATA_END.f16
	DW ANIM_DATA_END.f17
	DW ANIM_DATA_END.f18
	DW ANIM_DATA_END.f19
	DW ANIM_DATA_END.f20
	DW ANIM_DATA_END.f21
	DW ANIM_DATA_END.f22
	DW ANIM_DATA_END.f23
	DW ANIM_DATA_END.f24
	DW ANIM_DATA_END.f25
	DW ANIM_DATA_END.f26
	DW ANIM_DATA_END.f27
	DW ANIM_DATA_END.f28
	DW ANIM_DATA_END.f29
	DW ANIM_DATA_END.f30
	DW ANIM_DATA_END.f30
	DW ANIM_DATA_END.f30
ANIM_DATA_END_DELAYS:
	INCBIN "frames2/endanim_dur"
